{
    "tasks": ["Biology", "Medicine", "Psychology", "Computer_Science"],

    "annotation_task_name": "Match findings ([TASK])",

    #"base_task": "English",

    "base_config_file": "example-projects/match_finding/configs/match_finding.yaml",

    "base_dir": "example-projects/match_finding/",

    "data_files": [
        "example-projects/match_finding/data_files/pilot_data_[TASK].csv",
    ],

    "prestudy_files": [

    ],

    "surveyflow_path": "example-projects/match_finding/surveyflow/",
    "surveyflow_output_path": "example-projects/match_finding/surveyflow/[TASK]/",

    "output_annotation_dir": "example-projects/match_finding/annotation_output/pilot/[TASK]/"

}