{
    "port": 9001,

    "server_name": "potato annotator",

    "annotation_task_name": "info_shifts",

    # Potato will write the annotation file for all annotations to this
    # directory, as well as per-annotator output files and state information
    # necessary to restart annotation.
    "output_annotation_dir": "projects/info_changes/annotation_output/",

    # The output format for the all-annotator data. Allowed formats are:
    # * jsonl
    # * json (same output as jsonl)
    # * csv
    # * tsv
    #
    "output_annotation_format": "tsv",

    # If annotators are using a codebook, this will be linked at the top to the
    # instance for easy access
    "annotation_codebook_url": "",

    "data_files": [
      "projects/info_changes/data/pilot/medicine/score_[4, 5].tsv",
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text"
    },



    "surveyflow": {
      "on": true,
      "order": [
        "pre_annotation",
        "post_annotation"
      ],
      "pre_annotation": [
        "projects/info_changes/surveyflow/Welcome.jsonl",
        "projects/info_changes/surveyflow/Task.jsonl",
        "projects/info_changes/surveyflow/Consent.jsonl",
        "projects/info_changes/surveyflow/Navigation.jsonl",
      ],
      "post_annotation": [
          "projects/info_changes/surveyflow/Experience.jsonl",
          "projects/info_changes/surveyflow/End.jsonl",


      ],
      "testing": [

      ]
    },



    "user_config": {

      "allow_all_users": True,
      
      "users": [  ],
    },

    #list_as_text is used when the input text is actually a list of texts, usually used for best-worst-scaling or dialogue analysis
    "list_as_text": {
      "text_list_prefix_type": 'none', #whether automatically insert a prefix for each line, currently supporting 'number', 'alphabet', 'number'
      "horizontal": True,
    },

    "automatic_assignment": {
      "on": true,
      "output_filename": "task_assignment.json",
      "sampling_strategy": "random",
      "labels_per_instance": 3,
      "instance_per_annotator": 2,
      "test_question_per_annotator": 0,
      "users": [ ]
    },

    # How many seconds do you want the annotators spend on each instance, after
    # that, an alert will be sent per alert_time_each_instance seconds.
    "alert_time_each_instance": 10000000,

    "annotation_schemes": [
      # Changes in key entities & generalization
      {
        "annotation_type": "radio",
        "name": "changes-key-entity",
        "label_requirement": {"required":true},
        "description": "1a. The reported finding changes a key entity (e.g., affected demographics, variables, treatments) compared to the paper finding.",
        "horizontal": True,
        "labels": [
          {
            "name": "yes",
            "tooltip": "Key entities from the paper finding are changed. E.g., reporting that a finding applies to teenagers as opposed to toddlers or generalizing from dietary magnesium to unspecified magnesium intake."
          },
          {
            "name": "no",
            "tooltip": "The reporting accurately covers all key entities."
          }

        ],
        # If true, numbers [1-len(labels)] will be bound to each
        # label. Check box annotations with more than 10 are not supported
        # with this simple keybinding and will need to use the full item
        # specification to bind all labels to keys.
        "sequential_key_binding": True,
      },
      {
        "annotation_type": "highlight",
        "name": "key-entities",
        "description": '<span data-toggle="tooltip" data-html="true" data-placement="bottom" title="Double-click the highlighted section to delete your annotation.">1b. Highlight the entities that have been changed.</span>',
        "labels": [
          "Missing entity from the reported finding.", "Added entity in reported finding"
        ],

        # If true, numbers [1-len(labels)] will be bound to each
        # label. Highlight selection annotations with more than 10 are not supported
        # with this simple keybinding and will need to use the full item
        # specification to bind all labels to keys.
        "sequential_key_binding": True,
      },

      {
        "annotation_type": "radio",
        "name": "Level-of-generality",
        "description": "2a. The reported finding generalizes the results while the paper is more specific.",
        "label_requirement": {"required":true},
        "horizontal": True,
          "labels": [
            {
              "name": "yes",
              "tooltip": "E.g., the reporting generalizes a finding about diabetes type 2 in seniors to all people with diabetes."
            },
            {
              "name": "no",
              "tooltip": "The reporting accurately reports the finding with regards to the generality of the finding."
            }
          ],
        # If true, numbers [1-len(labels)] will be bound to each
        # label. Check box annotations with more than 10 are not supported
        # with this simple keybinding and will need to use the full item
        # specification to bind all labels to keys.
        "sequential_key_binding": True,
      },

        {
            "annotation_type": "highlight",
            "name": "key-entities",
            "description": '<span data-toggle="tooltip" data-html="true" data-placement="bottom" title="Double-click the highlighted section to delete your annotation.">2b. Highlight the parts of the text where you habve identified the generalization.</span>',
            "labels": [
                "Generalization"
            ],

          # If true, numbers [1-len(labels)] will be bound to each
          # label. Highlight selection annotations with more than 10 are not supported
          # with this simple keybinding and will need to use the full item
          # specification to bind all labels to keys.
            "sequential_key_binding": True,
        },



      # Changes in Certainty
        {
            "annotation_type": "radio",

          # This name gets used in reporting the annotation results
            "name": "how-certain-is-the-reported-finding",
            "label_requirement": {"required":true},

          # This text is shown to the user and can be a longer statement
            "description": "3a. In the reported finding, how do you rate the level of certainty used to describe the finding?",


            "labels": [
                {
                    "name": "Uncertain",
                    "tooltip": "E.g., 'Sunscreen might prevent skin cancer.'"
                },
                {
                    "name": "Somewhat uncertain",
                    "tooltip": "E.g., 'Sunscreen could prevent skin cancer.'"
                },
                {
                    "name": "Can't say",
                    "tooltip": "Neither certain nor uncertain."
                },
                {
                    "name": "Somewhat certain",
                    "tooltip": "E.g., 'Sunscreen can prevent skin cancer.'"
                },
                {
                    "name": "Certain",
                    "tooltip": "E.g., 'Sunscreen prevents skin cancer.'"
                },
            ],

          # If true, keys [1-size] will be bound to scale responses. Likert
          # scales larger than 10 are not supported with this simple
          # keybinding and will need to use the full item specification to
          # bind all scale points to keys.
            "sequential_key_binding": True,
        },

        {
            "annotation_type": "radio",

          # This name gets used in reporting the annotation results
            "name": "how-certain-is-the-paper-finding",
            "label_requirement": {"required":true},

          # This text is shown to the user and can be a longer statement
            "description": "3b. In the paper finding, how do you rate the level of certainty used to describe the finding?",

            "labels": [
              {
                "name": "Uncertain",
                "tooltip": "E.g., 'Sunscreen might prevent skin cancer.'"
              },
              {
                "name": "Somewhat uncertain",
                "tooltip": "E.g., 'Sunscreen could prevent skin cancer.'"
              },
              {
                "name": "Can't say",
                "tooltip": "Neither certain nor uncertain."
              },
              {
                "name": "Somewhat certain",
                "tooltip": "E.g., 'Sunscreen can prevent skin cancer.'"
              },
              {
                "name": "Certain",
                "tooltip": "E.g., 'Sunscreen prevents skin cancer.'"
              },
            ],

          # If true, keys [1-size] will be bound to scale responses. Likert
          # scales larger than 10 are not supported with this simple
          # keybinding and will need to use the full item specification to
          # bind all scale points to keys.
            "sequential_key_binding": True,
        },

        {
            "annotation_type": "highlight",
            "name": "certainty",
            "description": '<span data-toggle="tooltip" data-html="true" data-placement="bottom" title="Double-click the highlighted section to delete your annotation.">3c. Highlight the words or phrases that make the sentence more or less certain.</span>',
            "labels": [
              {
                "name": "certain",
                "tooltip": "This could be words like 'definitively', 'clearly', 'conclusively','undoubtedly'."
              },
              {
                "name": "uncertain",
                "tooltip": "This could be hedges like 'may', 'to some extend', 'probably', 'potentially', 'sometimes'."
              }

            ],

          # If true, numbers [1-len(labels)] will be bound to each
          # label. Highlight selection annotations with more than 10 are not supported
          # with this simple keybinding and will need to use the full item
          # specification to bind all labels to keys.
            "sequential_key_binding": True,
        },



      # Changes in Sensationalism
      {
        "annotation_type": "radio",
        "name": "reporting-is-sensational",
        "label_requirement": {"required":true},
        "description": "4a. The reported finding uses sensational language.",
        "horizontal": True,
          "labels": [
            {
              "name": "yes",
              "tooltip": "Reporting uses sensationalist language or style that aims to grab the readers' attention. E.g., 'miracle treatment', 'breakthrough study', 'cure',  'game changer',  'groundbreaking',  'home run',  'life-changing',  'life-saving',  'marvel', 'revolutionary',  'transformative']"
            },
            {
              "name": "no",
              "tooltip": "The reported finding neutrally reports the paper finding."
            }
          ],
        # If true, numbers [1-len(labels)] will be bound to each
        # label. Check box annotations with more than 10 are not supported
        # with this simple keybinding and will need to use the full item
        # specification to bind all labels to keys.
        "sequential_key_binding": True,
      },

        {
            "annotation_type": "radio",
            "name": "reporting-is-sensational",
            "description": "4b. The paper finding uses sensationalist language.",
            "label_requirement": {"required":true},
            "horizontal": True,
            "labels": [
                {
                    "name": "yes",
                    "tooltip": "Paper uses sensationalist language or style that aims to grab the readers' attention. E.g., 'miracle treatment', 'breakthrough study', 'cure',  'game changer',  'groundbreaking',  'home run',  'life-changing',  'life-saving',  'marvel', 'revolutionary',  'transformative']"
                },
                {
                    "name": "no",
                    "tooltip": "The paper neutrally reports the finding."
                }
            ],
          # If true, numbers [1-len(labels)] will be bound to each
          # label. Check box annotations with more than 10 are not supported
          # with this simple keybinding and will need to use the full item
          # specification to bind all labels to keys.
            "sequential_key_binding": True,
        },

        {
            "annotation_type": "highlight",
            "name": "sensational-language-cues",
            "description": '<span data-toggle="tooltip" data-html="true" data-placement="bottom" title="Double-click the highlighted section to delete your annotation.">4c. Highlight which words or phrases make the sentence sound sensationalist.</span>',
            "labels": [
              {
                "name": "Sensational language",
                "tooltip": "Sensationalist language or style that aims to grab the readers' attention. E.g., 'miracle treatment', 'breakthrough study', 'cure',  'game changer',  'groundbreaking',  'home run',  'life-changing',  'life-saving',  'marvel', 'revolutionary',  'transformative']"
              }
            ],

          # If true, numbers [1-len(labels)] will be bound to each
          # label. Highlight selection annotations with more than 10 are not supported
          # with this simple keybinding and will need to use the full item
          # specification to bind all labels to keys.
            "sequential_key_binding": True,
        },


      # Changes in Causality
      {
        "annotation_type": "radio",
        "name": "how-causal-is-the-reporting",
        "description": "5a. In the reported finding, what type of causal connection is described?",
        "label_requirement": {"required":true},

        # If true, display the labels horizontally
        "horizontal": True,

        "labels": [
          {
            "name": "No relation is stated",
            "tooltip": "No causal or correlational relation of any kind."
          },
          {
            "name": "Correlation",
            "tooltip": "The reported finding describes a correlation between two entities. E.g., 'Vitamin D levels are associated with extensive tiredness'"
          },
          {
            "name": "Causation",
            "tooltip": "The reported finding describes a causal relation between two entities. E.g., 'Low vitamin D levels cause extensive tiredness' or 'Tiredness might be caused by lack of vitamin D.'"
          },
        ],
        "sequential_key_binding": True,
      },


      {
        "annotation_type": "radio",
        "name": "how-causal-is-the-paper-finding",
        "description": "5b. In the paper finding, what type of causal connection is described?",
        "label_requirement": {"required":true},

        # If true, display the labels horizontally
        "horizontal": True,

        "labels": [
          {
            "name": "No relation is stated",
            "tooltip": "No causal or correlational relation of any kind."
          },
          {
            "name": "Correlation",
            "tooltip": "The paper finding describes a correlation between two entities. E.g., 'Vitamin D levels are associated with extensive tiredness'"
          },
          {
            "name": "Causation",
            "tooltip": "The paper finding describes a causal relation between two entities. E.g., 'Low vitamin D levels cause extensive tiredness' or 'Tiredness might be caused by lack of vitamin D.'"
          },
        ],
        "sequential_key_binding": True,
      },
        {
            "annotation_type": "highlight",
            "name": "causality-reporting",
            "description": '<span data-toggle="tooltip" data-html="true" data-placement="bottom" title="Double-click the highlighted section to delete your annotation.">5c. Highlight the phrases that indicate the relation.</span>',
            "labels": [
                "correlation", "causation"
            ],

          # If true, numbers [1-len(labels)] will be bound to each
          # label. Highlight selection annotations with more than 10 are not supported
          # with this simple keybinding and will need to use the full item
          # specification to bind all labels to keys.
            "sequential_key_binding": True,
        },




    ],

    # The html that changes the visualiztation for your task. Change this file
    # to influence the layout and description of your task. This is not a full
    # HTML page, just the piece that does lays out your task's pieces
    "html_layout": "templates/examples/plain_layout.html",

    # The core UI files for Potato. You should not need to change these normally.
    #
    # Exceptions to this might include:
    # 1) You want to add custom CSS/fonts to style your task
    # 2) Your layout requires additional JS/assets to render
    # 3) You want to support additional keybinding magic
    #
    "base_html_template": "templates/base_template.html",
    "header_file": "templates/header.html",

    # This is where the actual HTML files will be generated
    "site_dir": "potato/templates/",

}