{
    "port": 9001,

    "server_name": "potato annotator",

    "annotation_task_name": "Immigration Framing",

    "output_dir": "../output/",

    # NOTE: This is probably going to be a directory / DB at some point...
    "annotation_state_file": "output/annotation_state.jsonl",

    "codebook": "https://docs.google.com/document/d/1eXgaOZJDahhZLqYWbLTD_84-d1rnQ4M-bccer3HY6WI",

    "data_files": [
       "data/framing_tweets.json"
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text"
        
    },
    
    "users": [
        {"user_id": "0", "firstname": "David", "lastname": "Jurgens"},
        {"user_id": "1", "firstname": "Jiaxin", "lastname": "Pei"},
        {"user_id": "2", "firstname": "Naitian", "lastname": "Zhou"}
    ],

    "annotation_files": [
        "../data/examples"
    ],



    "annotation_schemes": [
        {
            "annotation_type": "multiselect",
            "name": "Issue General",
            "labels": [
                "Label 1",
                "Label 2",
                "Label 3",
                "Label 4",
                "Label 5"                
            ]
        },
        {
            "annotation_type": "multiselect",
            "name": "Issue Specific",
            "labels": [
                "Label 1",
                "Label 2",
                "Label 3"
            ]
            
        }

    ],


    # Visualization
    "html_template": "templates/multiple_choice.html",
    "header_file": "templates/header.html",

    # This is where the actual HTML files will be generated
    "site_dir": "site/",

    # comment    
    "state_update_rate": 1,


}
        
