{
    "port": 9001,

    "server_name": "potato annotator",

    "annotation_task_name": "Immigration Framing",

    "output_dir": "../output/",

    # NOTE: This is probably going to be a directory / DB at some point...
    "user_state_dir": "annotation_output",

    "annotation_codebook_url": "https://docs.google.com/document/d/1eXgaOZJDahhZLqYWbLTD_84-d1rnQ4M-bccer3HY6WI",

    "data_files": [
       "data/framing_tweets.json"
    ],

    "item_properties": {
        "id_key": "id_str",
        "text_key": "text"
        
    },
    
    "users": [
        {"user_id": "0", "firstname": "David", "lastname": "Jurgens"},
        {"user_id": "1", "firstname": "Jiaxin", "lastname": "Pei"},
        {"user_id": "2", "firstname": "Naitian", "lastname": "Zhou"}
    ],

    "annotation_files": [
        "../data/examples"
    ],

    "keyword_highlights_file": "config/frame_keywords.tsv",

    "annotation_schemes": [
        {
            "annotation_type": "multiselect",
            "name": "Issue-General",
            "labels": [
<<<<<<< HEAD
                { "name": "Economic",
                  "tooltip_file": "config/tooltips/ig_economic.html"
                },
                {
                  "name": "Capacity and Resources",
                  "tooltip_file": "config/tooltips/ig_capacity.html"
                 },

                { "name": "Morality and Ethics",
                  "tooltip_file": "config/tooltips/ig_morality.html"
                },
                
                { "name": "Fairness and Equality",
                  "tooltip_file": "config/tooltips/ig_fairness.html",
                },
                { "name": "Legality, Constitutionality, and Jurisdiction",
                  "tooltip": "",
                },
                { "name": "Crime and Punishment",
                  "tooltip": "",
                },
                { "name": "Security and Defense",
                  "tooltip": "",
                },
                { "name": "Health and Safety",
                  "tooltip": "",
                },
                { "name": "Quality of Life",
                  "tooltip": ""
                },
                { "name": "Cultural Identity",
                  "tooltip": ""
                },
                { "name": "Public Sentiment",
                  "tooltip": ""
                },
                { "name": "Political Factors and Implications",
                  "tooltip": ""
                },
                { "name": "Policy Prescription and Evaluation",
                  "tooltip": ""
                },
                { "name": "External Regulation and Reputation",
                  "tooltip": ""
                }
=======
                "Economic",
                "Capacity and Resources",
                "Morality and Ethics",
                "Fairness and Equality",
                "Legality, Constitutionality, and Jurisdiction",
                "Crime and Punishment",
                "Security and Defense",
                "Health and Safety",
                "Quality of Life",
                "Cultural Identity",                
                "Public Sentiment",
                "Political Factors and Implications",
                "Policy Prescription and Evaluation",
                "External Regulation and Reputation",                
>>>>>>> 7912e06ce2571b16b70b21c78b41c9bda749c503
            ]
        },

        {
            "annotation_type": "multiselect",
            "name": "Issue-Specific",
            "labels": [
                "Victim: Global Economy",
                "Victim: Humanitarian",
                "Victim: War",
                "Hero: Cultural Diversity",
                "Hero: Integration",
                "Hero: Worker",
                "Threat: Jobs",
                "Threat: Public Order",
                "Threat: Fiscal",
                {
                    "name": "Threat: National Cohesion",
                    "tooltip":
                    "<ul><li>Treats immigrant cultural differences (customs, religion, language) as a threat to national unity and social harmony
<li>Immigrants bring foreign customs and values that threaten to undermine the host country’s culture or national identity
<li>Immigrants are unassimilable
<li>Immigrants are diluting our culture, language, and values
<li>Emphasis on foreignness/otherness 
<li>Emphasis on some outside group taking over a country (e.g. Islamist takeover)
<ul><li>Shifting cultural values as result of immigration, takeover suggests that this is happening in a forced/unwanted way</ul>
<li>Includes claims that citizens’ political power is being lost or stolen
<ul><li>By illegal immigrants (illegally) voting</ul></ul>"
                }
            ]
            
        },

        {
            "annotation_type": "multiselect",
            "name": "Narrative",
            "labels": [
                {
                   "name": "Episodic",
                   "tooltip": "Message focuses on the place, event, or individual person involved",
                },
                {
                  "name": "Thematic",
                  "tooltip": "More abstract, generic views of an event or issue"
                },
            ]
            
        }

    ],


    # Visualization
    "html_template": "templates/multiple_choice.html",
    "header_file": "templates/header.html",

    # This is where the actual HTML files will be generated
    "site_dir": "potato/templates/",

    # comment    
    "state_update_rate": 1,


}
        
