{
  "server_name": "potato annotator",
  "annotation_task_name": "GIF Reply Evaluation",
  "output_dir": "../output/",

  # NOTE: This is probably going to be a directory / DB at some point...
  "user_state_dir": "annotation_output",
  "annotation_codebook_url": "/",
  "data_files":
    [
      "potato/data/tagbased-annotation-pairs-1000-random-subset.json",
      "potato/data/clipv-annotation-pairs-1000-random-subset.json",
    ],

  "item_properties": { "id_key": "id", "text_key": "text" },

  "users":
    [
      { "user_id": "0", "firstname": "David", "lastname": "Jurgens" },
      { "user_id": "1", "firstname": "Jiaxin", "lastname": "Pei" },
      { "user_id": "2", "firstname": "Naitian", "lastname": "Zhou" },
      { "user_id": "3", "firstname": "Xingyao", "lastname": "Wang" },
    ],

  "annotation_files": ["../data/examples"],

  # "keyword_highlights_file": "config/frame_keywords.tsv",

  "annotation_schemes":
    [
      {
        "annotation_type": "multiselect",
        "single_select": "False",
        "name": "Tweet-GIF Match",
        "video_as_label": "True",
        "labels":
          [
            {
              "name": "{{instance_obj.gifs[0]}}",
              "videopath": "/file/{{instance_obj.gifs_path[0]}}",
              "key_value": "1",
            },
            {
              "name": "{{instance_obj.gifs[1]}}",
              "videopath": "/file/{{instance_obj.gifs_path[1]}}",
              "key_value": "2",
            },
            {
              "name": "{{instance_obj.gifs[2]}}",
              "videopath": "/file/{{instance_obj.gifs_path[2]}}",
              "key_value": "3",
            },
            {
              "name": "{{instance_obj.gifs[3]}}",
              "videopath": "/file/{{instance_obj.gifs_path[3]}}",
              "key_value": "4",
            },
            {
              "name": "{{instance_obj.gifs[4]}}",
              "videopath": "/file/{{instance_obj.gifs_path[4]}}",
              "key_value": "5",
            },
            {
              "name": "{{instance_obj.gifs[5]}}",
              "videopath": "/file/{{instance_obj.gifs_path[5]}}",
              "key_value": "6",
            },
            {
              "name": "{{instance_obj.gifs[6]}}",
              "videopath": "/file/{{instance_obj.gifs_path[6]}}",
              "key_value": "7",
            },
            {
              "name": "{{instance_obj.gifs[7]}}",
              "videopath": "/file/{{instance_obj.gifs_path[7]}}",
              "key_value": "8",
            },
            {
              "name": "{{instance_obj.gifs[8]}}",
              "videopath": "/file/{{instance_obj.gifs_path[8]}}",
              "key_value": "9",
            },
            {
              "name": "{{instance_obj.gifs[9]}}",
              "videopath": "/file/{{instance_obj.gifs_path[9]}}",
              "key_value": "0",
            },
          ],
      },
    ],

  # Visualization
  "html_template": "templates/single_multiple_choice.html",
  "header_file": "templates/header.html",

  # This is where the actual HTML files will be generated
  "site_dir": "potato/templates/",

  # comment
  "state_update_rate": 1,
}
