{
    "port": 9001,

    "server_name": "potato annotator",

    "annotation_task_name": "Certainty-bio",

    # Potato will write the annotation file for all annotations to this
    # directory, as well as per-annotator output files and state information
    # necessary to restart annotation.
    "output_annotation_dir": "projects/certainty-bio/annotation_output/",

    # The output format for the all-annotator data. Allowed formats are:
    # * jsonl
    # * json (same output as jsonl)
    # * csv
    # * tsv
    #
    "output_annotation_format": "tsv",

    # If annotators are using a codebook, this will be linked at the top to the
    # instance for easy access
    "annotation_codebook_url": "https://docs.google.com/document/d/1bNoa1V_pMVqjQfp0vC1gUVQ9N6b1L_a25wKt8enQgn8/edit?usp=sharing",

    "data_files": [
      "data/all-data-to-be-annotated/Biology/separated/Biology_missing.tsv",
      #"data/all-data-to-be-annotated/Biology/separated/Biology.tsv"
      
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text"
    },



    "surveyflow": {
      "on": true,
      "order": [
        "pre_annotation",
        "post_annotation"
      ],
      "pre_annotation": [
        "projects/certainty-bio/surveyflow/Welcome.jsonl",
        "projects/certainty-bio/surveyflow/Task.jsonl",
        "projects/certainty-bio/surveyflow/Certainty.jsonl",
        "projects/certainty-bio/surveyflow/Certainty Examples.jsonl",
        "projects/certainty-bio/surveyflow/Navigation.jsonl",
        "projects/certainty-bio/surveyflow/Consent.jsonl",
      ],
      "post_annotation": [
          "projects/certainty-bio/surveyflow/Experience.jsonl",
          "projects/certainty-bio/surveyflow/End.jsonl",


      ],
      "testing": [
             "projects/certainty-bio/surveyflow/attention-certainty.jsonl",

      ]
    },



    "user_config": {

      "allow_all_users": True,
      
      "users": [  ],
    },

    #list_as_text is used when the input text is actually a list of texts, usually used for best-worst-scaling or dialogue analysis
    "list_as_text": {
      "text_list_prefix_type": 'none', #whether automatically insert a prefix for each line, currently supporting 'number', 'alphabet', 'number'
      "horizontal": True,
    },

    "automatic_assignment": {
      "on": true,
      "output_filename": "task_assignment.json",
      "sampling_strategy": "ordered", #"random" is the alternative
      "labels_per_instance": 1,
      "instance_per_annotator": 12,
      "test_question_per_annotator": 2,
      "users": [ ]
    },

    # How many seconds do you want the annotators spend on each instance, after
    # that, an alert will be sent per alert_time_each_instance seconds.
    "alert_time_each_instance": 10000000,

    "annotation_schemes": [

      {
            "annotation_type": "radio",

          # This name gets used in reporting the annotation results
            "name": "how-certain-is-the-finding",
            "label_requirement": {"required":true},

          # This text is shown to the user and can be a longer statement
            "description": '<span data-toggle="tooltip" data-html="true" data-placement="bottom" title="Certainty or uncertainty can be expressed with respect to various aspects. Things to look out for include: (un)certainty towards specific numbers/quantities (They found that approximately 50 % of participants …), the extent to which a given finding applies (The effect was mainly observed for teenagers.), the probability that something applies, occurs or is associated (... is possibly associated with …).">How do you rate the level of certainty the author uses to describe the finding?</span>',

            "labels": [
              {
                "name": "Uncertain",
                "tooltip": "E.g., 'Sunscreen might prevent skin cancer.' or 'Overconsumption of sugar may have negative effects on health.', 'Further research is necessary to understand ...'"
              },
              {
                "name": "Somewhat uncertain",
                "tooltip": "E.g., 'Sunscreen could prevent skin cancer.' or 'Overconsumption of sugar can cause diabetes.', 'The functionality possibly depends on ....'"
              },
              {
                "name": "Somewhat certain",
                "tooltip": "E.g., 'Sunscreen can prevent skin cancer.' or 'The analysis suggests that papers with short titles receive more citations'"
              },
              {
                "name": "Certain",
                "tooltip": "E.g., 'Sunscreen prevents skin cancer.' or 'Papers with shorter titles get more citations', '... meaning that this treatment should be used ...'"
              },
            ],

          # If true, keys [1-size] will be bound to scale responses. Likert
          # scales larger than 10 are not supported with this simple
          # keybinding and will need to use the full item specification to
          # bind all scale points to keys.
            "sequential_key_binding": True,
        },

        {
            "annotation_type": "highlight",
            "name": "certainty",
            "description": '<span data-toggle="tooltip" data-html="true" data-placement="bottom" title="To delete your annotation, double-click the highlighting in the text.">Click the checkbox and mark the words or phrases in the finding that express the author''s certainty.</span>',
            "labels": [

              {
                "name": "Words indicating certainty",
                "tooltip": "This could be words like 'definitively', 'clearly', 'conclusively','undoubtedly'"
              }

            ],

          # If true, numbers [1-len(labels)] will be bound to each
          # label. Highlight selection annotations with more than 10 are not supported
          # with this simple keybinding and will need to use the full item
          # specification to bind all labels to keys.
            "sequential_key_binding": True,
        },

        {
            "annotation_type": "highlight",
            "name": "uncertainty",
            "description": '<span data-toggle="tooltip" data-html="true" data-placement="bottom" title="To delete your annotation, double-click the highlighting in the text.">Click the checkbox and mark the words or phrases in the finding that express the author''s uncertainty.</span>',
            "labels": [
                {
                    "name": "Words indicating uncertainty",
                    "tooltip": "This could be hedges like 'may', 'to some extent', 'probably', 'potentially', 'sometimes', 'possibly', 'mainly'."
                }

            ],

          # If true, numbers [1-len(labels)] will be bound to each
          # label. Highlight selection annotations with more than 10 are not supported
          # with this simple keybinding and will need to use the full item
          # specification to bind all labels to keys.
            "sequential_key_binding": True,
        },

        ],








    # The html that changes the visualiztation for your task. Change this file
    # to influence the layout and description of your task. This is not a full
    # HTML page, just the piece that does lays out your task's pieces
    "html_layout": "templates/examples/plain_layout.html",

    # The core UI files for Potato. You should not need to change these normally.
    #
    # Exceptions to this might include:
    # 1) You want to add custom CSS/fonts to style your task
    # 2) Your layout requires additional JS/assets to render
    # 3) You want to support additional keybinding magic
    #
    "base_html_template": "templates/base_template.html",
    "header_file": "templates/header.html",

    # This is where the actual HTML files will be generated
    "site_dir": "potato/templates/",

  #defining the ways annotators entering the annotation system
    "login": {
        "type": 'url_direct',    #can be 'password' or 'url_direct'
        "url_argument": 'PROLIFIC_PID' # when the login type is set to 'url_direct', 'url_argument' must be setup for a direct url argument login
    },

    "ui": {
      "spans": {
        "span_colors":
          {
            "Added element in reported finding.": "(204,121,167)",
            "Missing element from the reported finding.": "(0, 114,178)",
            "Generalization": "(213,94,0)",
            "Words indicating certainty": "(240,228,66)",
            "Words indicating uncertainty": "(0,158,115)",
            "Sensational language": "(86,180,233)",
            "Causation": "(230,159,0)",
            "Correlation": "(78,76,74)",
            "Explicit mentions of no relation": "(172,238,180)",
          }
      }
    }


}
