{
    "tasks": ["Biology", "Medicine", "Psychology", "Physics", "Chemistry", "Computer_Science"],

    "annotation_task_name": "Match findings ([TASK])",

    #"base_task": "English",

    "base_config_file": "projects/match_finding/configs/match_finding.yaml",

    "base_dir": "projects/match_finding/",

    "data_files": [
        "projects/match_finding/data_files/pilot_data_[TASK].csv",
        "projects/match_finding/data_files/prestudy/prestudy_data_[TASK].csv"
    ],

    "prestudy_files": [

    ],

    "surveyflow_path": "projects/match_finding/surveyflow/",
    "surveyflow_output_path": "projects/match_finding/surveyflow/[TASK]/",

    #"multitask_guideline_file": "projects/multilingual-tweet-intimacy/Multilingual_Intimacy_Guideline.csv",

    "output_annotation_dir": "projects/match_finding/annotation_output/pilot/[TASK]/"

}